import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00302b",
        outline: "#859585",
        "primary-fixed": "#62ff96",
        primary: "#75ff9e",
        "on-tertiary": "#370096",
        "primary-container": "#00e676",
        "inverse-on-surface": "#2d3137",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#00e475",
        "secondary-fixed-dim": "#66d9cc",
        "on-surface": "#dfe2eb",
        "surface-container-low": "#181c22",
        "tertiary-fixed": "#e8deff",
        "on-surface-variant": "#bacbb9",
        "on-primary-container": "#00612e",
        "inverse-surface": "#dfe2eb",
        "error-container": "#93000a",
        "surface-tint": "#00e475",
        "inverse-primary": "#006d35",
        "secondary-container": "#1ea296",
        "surface-variant": "#31353c",
        "outline-variant": "#3b4a3d",
        "on-error": "#690005",
        error: "#ffb4ab",
        "on-primary-fixed": "#00210b",
        "on-background": "#dfe2eb",
        surface: "#10141a",
        "surface-container-high": "#262a31",
        "on-tertiary-fixed": "#20005f",
        "surface-container-lowest": "#0a0e14",
        secondary: "#66d9cc",
        "surface-bright": "#353940",
        "surface-container-highest": "#31353c",
        "surface-container": "#1c2026",
        "tertiary-container": "#cfbfff",
        "on-tertiary-container": "#5d21df",
        "on-secondary-fixed-variant": "#005049",
        "on-secondary-fixed": "#00201d",
        "on-tertiary-fixed-variant": "#4f00d0",
        "on-secondary": "#003732",
        "tertiary-fixed-dim": "#cdbdff",
        tertiary: "#e9dfff",
        background: "#10141a",
        "surface-dim": "#10141a",
        "on-primary-fixed-variant": "#005226",
        "on-primary": "#003918",
        "secondary-fixed": "#84f5e8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Berkeley Mono", "monospace"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
